#!/usr/bin/env bash

# Check that the API key was provided
if [ -z "$OPENAI_API_KEY" ]; then
    echo "Error: Please export \$OPENAI_API_KEY."
    exit 1
fi

PROMPT='Whats on your mind?'
echo $PROMPT
read -p '>>> ' INPUT

response=$(curl -s https://api.openai.com/v1/completions \
   -H 'Content-Type: application/json' \
   -H "Authorization: Bearer $OPENAI_API_KEY" \
   -d "{
   \"model\": \"text-davinci-003\",
   \"prompt\": \"$INPUT\",
   \"max_tokens\": 2048,
   \"temperature\": 0
}")

response_text=$(echo $response | jq -r ".choices[0].text" )
echo $response_text
